#!/usr/bin/env python3
"""Keep a "current locations" table in a document that cites historical paths.

`outputs/SUPERSEDED.md` names files by their paths at `research-final`
(`cd03af9c`); several moved in the 2026-10-05 restructure. This script finds
every backticked repository path in the document, resolves it through
`docs/research-record/MOVES.json`, and writes the moved ones into a table
between markers at the top of the document, so a reader never has to open
MOVES.md by hand.

    python scripts/current_locations.py outputs/SUPERSEDED.md           # update
    python scripts/current_locations.py outputs/SUPERSEDED.md --check   # exit 1 if stale
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from repo_paths import ROOT, resolve  # noqa: E402

BEGIN, END = "<!-- current-locations:begin -->", "<!-- current-locations:end -->"
TOKEN = re.compile(r"`([A-Za-z0-9_./*\-]+\.(?:md|json|jsonl|csv|log|txt)|[A-Za-z0-9_.\-]+(?:/[A-Za-z0-9_.*\-]+)+/?)`")


def table(text: str) -> str:
    body = text.split(END, 1)[-1] if END in text else text
    rows, seen = [], set()
    for rel in TOKEN.findall(body):
        if rel in seen or "*" in rel:
            continue
        seen.add(rel)
        if (ROOT / rel).exists():
            continue
        new = resolve(rel)
        if new.exists():
            rows.append(f"| `{rel}` | `{new.relative_to(ROOT).as_posix()}` |")
        else:
            rows.append(f"| `{rel}` | not a file in the tree (pattern or description) |")
    head = ("**Current locations** (generated by `scripts/current_locations.py` from "
            "`docs/research-record/MOVES.json`; paths in the text below are as of "
            "`research-final`):\n\n| cited path | current path |\n|---|---|\n")
    return BEGIN + "\n" + head + "\n".join(rows) + "\n" + END


def main() -> int:
    path = ROOT / sys.argv[1]
    text = path.read_text()
    block = table(text)
    if BEGIN in text:
        new = text[:text.index(BEGIN)] + block + text[text.index(END) + len(END):]
    else:
        first_break = text.index("\n\n") + 2
        new = text[:first_break] + block + "\n\n" + text[first_break:]
    if "--check" in sys.argv:
        ok = new == text
        print(("ok  " if ok else "FAIL") + f" current-locations table in {sys.argv[1]}")
        return 0 if ok else 1
    path.write_text(new)
    print(f"updated {sys.argv[1]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
