#!/usr/bin/env python3
"""Generate the Exp 7 sensitivity table in docs/CALIBRATION.md from the artifacts.

For every Exp 7 level that perturbs a calibration-register parameter, the table
gives the frozen Stage 1 fixed-plan F1 (pre-specified; change in modeled
unserved demand of the certified Exp 1 plan against the current plan, at that
level) with its pre-specified magnitude band, and, where it exists, the post hoc
re-optimized F1 in the R1_H60 decision space. Nothing is typed.

    python scripts/make_calibration_tables.py           # rewrite the block
    python scripts/make_calibration_tables.py --check   # exit 1 if stale
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "docs" / "CALIBRATION.md"
BEGIN, END = "<!-- calibration-sensitivity:begin -->", "<!-- calibration-sensitivity:end -->"
LEVELS = "outputs/exp7/EXP7_LEVELS.json"
STAGE1 = "outputs/exp7/stage1/EXP7_STAGE1_ANALYSIS.json"
DSPACE = "outputs/exp7/EXP7_F1_DECISION_SPACE.json"

#: register parameter -> Exp 7 levels that perturb it
MAP = [
    ("walking speed", ["A6_WALKSPD85"]),
    ("access radius and transfer walking cap", ["A6_MAXWALK75"]),
    ("transfer penalty", ["A5_TP050", "A5_TP200"]),
    ("λ (unserved weight multiplier)", ["A5_LAM1", "A5_LAM4"]),
    ("retention curve", ["A8_ZERO150", "A8_FLOOR0"]),
    ("demand: non-commute travel", ["A1_NC025", "A1_NC050", "A1_NC100"]),
    ("demand: LODES sampling (bootstrap, 20 draws)", ["A2_BOOT%02d" % i for i in range(1, 21)]),
    ("running times", ["A3_RT110", "A3_RT120", "A3_RTNOISE"]),
    ("waiting model (Class B: Model A)", ["B1_COMMONLINES"]),
]


#: where the level's own rationale text is known to be wrong (errata), say what ran
OVERRIDE_TEXT = {
    "B1_COMMONLINES": "Model A waiting (`common_lines = pattern`); the as-issued cross-route "
                      "common-lines item was not implemented (Exp 7 errata E16; report §9 R13)",
}


def J(p):
    return json.loads((ROOT / p).read_text())


def table() -> str:
    levels = {lv["name"]: lv for lv in J(LEVELS)["levels"]}
    per = J(STAGE1)["classification"]["F1"]["per_level"]
    base = J(STAGE1)["classification"]["F1"]["base"]
    ds = {r["level"]: r for r in J(DSPACE)["rows"]}
    rows = ["| parameter | Exp 7 level | perturbation | F1 fixed plan, pre-specified (band) | F1 re-optimized, R1_H60, post hoc |",
            "|---|---|---|---|---|",
            f"| (reference) | BASE | none | {base:+.2f}% | "
            + (f"{ds['BASE']['cells']['R1_H60']['f1_pct']:+.2f}%" if "BASE" in ds else "not run") + " |"]
    for param, names in MAP:
        if names[0].startswith("A2_BOOT"):
            vals = [per[n]["value"] for n in names if n in per]
            bands = sorted({per[n]["band"] for n in names if n in per})
            rows.append(f"| {param} | A2_BOOT01–20 | bootstrap resample of LODES OD | "
                        f"{min(vals):+.2f}% to {max(vals):+.2f}% ({'; '.join(bands)}) | not selected |")
            continue
        for n in names:
            lv = levels[n]
            pert = "; ".join(f"`{k}` = {v}" for k, v in lv["overrides"]) or \
                lv["rationale"].split(":", 1)[1].split(". ")[0].strip().rstrip(".")
            pert = OVERRIDE_TEXT.get(n, pert).replace("|", "\\|")
            if n in per:
                fx = f"{per[n]['value']:+.2f}% ({per[n]['band']})"
            else:
                fx = "reported separately (Class B, model disagreement)"
            ro = (f"{ds[n]['cells']['R1_H60']['f1_pct']:+.2f}%" if n in ds
                  and "R1_H60" in ds[n].get("cells", {}) else "not re-optimized")
            rows.append(f"| {param} | {n} | {pert} | {fx} | {ro} |")
    head = ("Generated by `scripts/make_calibration_tables.py` from `" + STAGE1 + "`, `"
            + LEVELS + "` and `" + DSPACE + "`. F1 = change in modeled unserved demand "
            "(certified Exp 1 plan vs current plan, λ = 2 unless the level changes λ); "
            "negative is favourable.\n\n")
    return BEGIN + "\n" + head + "\n".join(rows) + "\n" + END


def main() -> int:
    text = DOC.read_text()
    new = text[:text.index(BEGIN)] + table() + text[text.index(END) + len(END):]
    if "--check" in sys.argv:
        ok = new == text
        print(("ok  " if ok else "FAIL") + " calibration sensitivity table")
        return 0 if ok else 1
    DOC.write_text(new)
    print("updated docs/CALIBRATION.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
